accounts/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
    path("profile/", views.profile, name="profile"),
]

django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('', include('vehicles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name='index'),
]

vehicles/urls.py
from django.urls import path
from . import views

app_name = "vehicle"

urlpatterns = [
    path('vehicle/<int:vehicle_id>/design', views.vehicle_custom, name='vehicle_custom'),
    path('vehicle/checkout', views.vehicle_checkout, name='vehicle_checkout'),
    path('confirmOrder/', views.confirmOrder, name="confirmOrder")
]

accounts/models.py
from django.db import models
from vehicles.models import VehicleCustom
from django.contrib.auth.models import User

# Create your models here.
class Orders(models.Model):
    order_user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_vehicle = models.ForeignKey(VehicleCustom, on_delete=models.CASCADE)
    order_date = models.DateField(auto_now_add=True)
    order_time = models.TimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2)
    order_payment = models.CharField(max_length=200, default="Card")

home/models.py
from django.db import models

# Create your models here.

vehicles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Vehicle(models.Model):
    vehicle_name = models.CharField(max_length=255)
    vehicle_range = models.CharField(max_length=10)
    vehicle_topspeed = models.CharField(max_length=10)
    vehicle_acceleration = models.CharField(max_length=10)
    vehicle_price = models.DecimalField(max_digits=10, decimal_places=2)
    vehicle_home_image = models.URLField()
    vehicle_image_1 = models.URLField()
    vehicle_image_1_name = models.CharField(max_length=100)
    vehicle_image_2 = models.URLField()
    vehicle_image_2_name = models.CharField(max_length=100)
    vehicle_image_3 = models.URLField()
    vehicle_image_3_name = models.CharField(max_length=100)
    vehicle_image_4 = models.URLField()
    vehicle_image_4_name = models.CharField(max_length=100)
    vehicle_wheel_1_image = models.URLField()
    vehicle_wheel_1_name = models.CharField(max_length=100)
    vehicle_wheel_2_image = models.URLField()
    vehicle_wheel_2_name = models.CharField(max_length=100)

class VehicleCustom(models.Model):
    vehicle_custom_vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    vehicle_custom_user = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle_custom_wheels = models.CharField(max_length=255)
    vehicle_custom_color = models.CharField(max_length=255)
    vehicle_custom_interior = models.CharField(max_length=255)

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'username':"Username" ,'email': 'Email'}

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import SignUpForm
from vehicles.models import Vehicle
from .models import Orders

# Create your views here.
def signin(request):
    vehicles = Vehicle.objects.all()
    if request.user.is_authenticated:
        return redirect('account:profile')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            login(request, user)
            return redirect('account:profile')
    else:
        form = AuthenticationForm() 
    return render(request, 'signin.html', {'form': form, 'vehicles': vehicles})

def signup(request):
    vehicles = Vehicle.objects.all()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('account:signin')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form, 'vehicles': vehicles})


def signout(request):
    logout(request)
    return redirect('account:signin')

def profile(request):
    vehicles = Vehicle.objects.all()
    if not request.user.is_authenticated:
        return redirect("account:signin")

    orders = Orders.objects.filter(order_user=request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            msg = "Password changed successfully!"
        else:
            msg = "Password not changed! Requirements not met."
        return render(request, 'profile.html', {'form': form, 'msg': msg, 'vehicles':vehicles, 'orders':orders})
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profile.html', {'form': form, 'vehicles':vehicles, 'orders':orders})

home/views.py
from django.shortcuts import render
from vehicles.models import Vehicle

# Create your views here.
def index(request):
    vehicles = Vehicle.objects.all()
    return render(request, 'index.html', {'vehicles': vehicles})

vehicles/views.py
from django.shortcuts import redirect, render
from accounts.models import Orders
from vehicles.models import Vehicle, VehicleCustom

# Create your views here.
def vehicle_custom(request, vehicle_id):
    vehicles = Vehicle.objects.all()
    vehicle = Vehicle.objects.get(id=vehicle_id)
    return render(request, 'design.html', {'vehicle': vehicle, 'vehicles': vehicles})

def vehicle_checkout(request):
    if not request.user.is_authenticated:
        return redirect("account:signin")
    if request.method == 'POST':
        veh_id = request.POST['veh_id']
        vehicle = Vehicle.objects.get(id=veh_id)
        user = request.user
        custom_wheels = request.POST['wheelOptions']
        custom_color = request.POST['colorOptions']
        custom_interior = request.POST['interiorOptions']
        custom_vehicle = VehicleCustom.objects.create(vehicle_custom_vehicle=vehicle, vehicle_custom_user=user, vehicle_custom_wheels=custom_wheels, vehicle_custom_color=custom_color, vehicle_custom_interior=custom_interior)
        print(custom_vehicle)
        return render(request, 'vehicle_checkout.html', {'vehicle': vehicle, 'custom_vehicle': custom_vehicle})
    return render(request, 'vehicle_checkout.html')

def confirmOrder(request):
    if not request.user.is_authenticated:
        return redirect("account:signin")
    if request.method == 'POST':
        order_user = request.user
        order_vehicle_id = request.POST['custom_veh_id']
        order_vehicle = VehicleCustom.objects.get(id=order_vehicle_id)
        order_total = request.POST['total']
        order = Orders.objects.create(order_user=order_user, order_vehicle=order_vehicle, order_total=order_total)
    return redirect('account:profile')

accounts/templates/signin.html
{% extends "base.html" %}
{% load static %}
{% block title %}Sign In{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'signin.css' %}">
{% endblock css %}
{% block content %}
    <div class="container">
        <div class="content">
            <div class="card-container mx-auto">
                <div class="card w-100 h-100">
                    <div class="card-body row p-0">
                        <div class="col">
                            <div class="bg-dark rounded h-100 p-0 m-0 w-100">
                                <div class="d-flex justify-content-center text-center align-items-center h-100">
                                    <div class="text-white">
                                        <h1 class="fw-bold">Welcome to Tesla</h1>
                                        <h6 class="mt-5">No account yet?</h6>
                                        <a href="{% url 'account:signup' %}">
                                            <button type="button" class="btn btn-outline-light text-white">Sign up</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="p-4">
                            <h1 class="text-center fw-bold">Sign In</h1>
                            <p class="lead text-center">Please login to continue</p>
                            <form action="" method="post" class="form">
                                    {% csrf_token %}
                                    <small class="text-danger">{{ form.non_field_errors | striptags }}</small>
                                    {% for field in form %}
                                        <div class="form-group mt-4">
                                            {{ field.label_tag }}
                                            {{ field }}
                                        </div>
                                    {% endfor %}
                                <button type="submit" class="btn btn-primary position-absolute btn-signin">Sign In</button>
                            </form>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
    <script src="{% static 'nav.js' %}"></script>
{% endblock content %}

home/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Tesla | Electric Cars & Clean Energy
{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock css %}
{% block content %}
    <div class="container-fluid content">
        <div class="row min-vh-100">
            {% for vehicle in vehicles %}
                <div class="col-12 p-0">
                    <div class="section-hero text-center"
                         style="background-image: url('{{ vehicle.vehicle_home_image }}')">
                        <h1 class="pt-5 section-title">{{ vehicle.vehicle_name }}</h1>
                        <div style="height: 70%;"></div>
                        <a class="btn btn-primary section-order"
                           href="{% url 'vehicle:vehicle_custom' vehicle.id %}">Custom Order</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
    <script src="{% static 'nav.js' %}"></script>
{% endblock content %}

home/templates/navbar.html
{% load static %}
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light p-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:index' %}">
                <svg class="brand-logo"
                     viewBox="0 0 342 35"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill="currentColor" d="M0 .1a9.7 9.7 0 0 0 7 7h11l.5.1v27.6h6.8V7.3L26 7h11a9.8 9.8 0 0 0 7-7H0zm238.6 0h-6.8v34.8H263a9.7 9.7 0 0 0 6-6.8h-30.3V0zm-52.3 6.8c3.6-1 6.6-3.8 7.4-6.9l-38.1.1v20.6h31.1v7.2h-24.4a13.6 13.6 0 0 0-8.7 7h39.9v-21h-31.2v-7zm116.2 28h6.7v-14h24.6v14h6.7v-21h-38zM85.3 7h26a9.6 9.6 0 0 0 7.1-7H78.3a9.6 9.6 0 0 0 7 7m0 13.8h26a9.6 9.6 0 0 0 7.1-7H78.3a9.6 9.6 0 0 0 7 7m0 14.1h26a9.6 9.6 0 0 0 7.1-7H78.3a9.6 9.6 0 0 0 7 7M308.5 7h26a9.6 9.6 0 0 0 7-7h-40a9.6 9.6 0 0 0 7 7">
                    </path>
                </svg>
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ms-auto ">
                    <li class="nav-item">
                        <a class="nav-link mx-2 dropdown-toggle dropdown-toggle-vh"
                           data-bs-toggle="collapse"
                           href="#subheader-vh"
                           role="button"
                           aria-expanded="false"
                           aria-controls="subheader-vh"
                           aria-current="page"
                           href="#">Vehicles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-2 dropdown-toggle dropdown-toggle-dscvr"
                           data-bs-toggle="collapse"
                           href="#subheader-dscvr"
                           role="button"
                           aria-expanded="false"
                           aria-controls="subheader-dscvr"
                           href="#">Discover</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto d-none d-lg-inline-flex">
                    <li class="nav-item mx-2">
                        <a class="nav-link text-dark h5" href="{% url 'account:profile' %}"><i class="h3 mt-3 fa-solid fa-user"></i></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item mx-2">
                        <a class="nav-link text-dark h5" href="{% url 'account:signout' %}"><i class="h3 mt-3 fas fa-sign-out"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="collapse collapse-vehicles bg-white mt-0" id="subheader-vh">
        <div class="subheader-vh p-3">
            <div class="container">
                <div class="row">
                    {% for vehicle in vehicles %}
                    <div class="col-6 col-md-4 text-center top-seller-nav">
                        <img class="sub-prod-img img"
                             src="{{ vehicle.vehicle_image_1 }}"
                             alt="model-3"
                             width="auto"
                             height="150">
                        <h4 class="sub-prod-name">{{ vehicle.vehicle_name }}</h4>
                        <a class="sub-prod-action" href="{% url 'vehicle:vehicle_custom' vehicle.id %}">Order</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="collapse collapse-discover bg-white mt-0" id="subheader-dscvr">
        <div class="subheader-dscvr p-3">
            <div class="container text-center">
                <a class="text-decoration-none text-reset" href="https://maps.app.goo.gl/P4Uqa62oqZRVSZVJ7" target="_blank">
                    <img class="img"
                         src="https://www.svgrepo.com/show/38705/location-pin.svg"
                         alt="find us"
                         width="auto"
                         height="80">
                    <h4 class="mt-3 text-decoration-underline">Find Us</h4>
                </a>
            </div>
        </div>
    </div>
</div>

vehicles/templates/design.html
{% extends "base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'design.css' %}">
{% endblock css %}
{% block title %}
  Design Your Car
{% endblock title %}
{% block content %}
  <div class="container-fluid content">
    <div class="row">
      <div class="col-md-9">
        <h1>Design Your Car</h1>
        <div id="carouselVeh" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button"
                    data-bs-target="#carouselVeh"
                    data-bs-slide-to="0"
                    class="active bg-dark"
                    aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button"
                    data-bs-target="#carouselVeh"
                    data-bs-slide-to="1"
                    aria-label="Slide 2"
                    class="bg-dark"></button>
            <button type="button"
                    data-bs-target="#carouselVeh"
                    data-bs-slide-to="2"
                    aria-label="Slide 3"
                    class="bg-dark"></button>
            <button type="button"
                    data-bs-target="#carouselVeh"
                    data-bs-slide-to="3"
                    aria-label="Slide 4"
                    class="bg-dark"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{ vehicle.vehicle_image_1 }}"
                   class="d-block w-100"
                   alt="..."
                   width="auto"
                   height="auto">
            </div>
            <div class="carousel-item">
              <img src="{{ vehicle.vehicle_image_2 }}"
                   class="d-block w-100"
                   alt="..."
                   width="auto"
                   height="auto">
            </div>
            <div class="carousel-item">
              <img src="{{ vehicle.vehicle_image_3 }}"
                   class="d-block w-100"
                   alt="..."
                   width="auto"
                   height="auto">
            </div>
            <div class="carousel-item">
              <img src="{{ vehicle.vehicle_image_4 }}"
                   class="d-block w-100"
                   alt="..."
                   width="auto"
                   height="auto">
            </div>
          </div>
          <button class="carousel-control-prev"
                  type="button"
                  data-bs-target="#carouselVeh"
                  data-bs-slide="prev">
            <span class="carousel-control-prev-icon bg-dark rounded" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next"
                  type="button"
                  data-bs-target="#carouselVeh"
                  data-bs-slide="next">
            <span class="carousel-control-next-icon bg-dark rounded" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
      <div class="col-md-3 overflow-auto">
        <div class="container text-center p-5">
          <h1>{{ vehicle.vehicle_name }}</h1>
          <div class="stat">
            <div class="row mt-5 h-50">
              <div class="col-md-4">
                <h5>{{ vehicle.vehicle_range }}</h5>
                <small>Range (WLTP)</small>
              </div>
              <div class="col-md-4">
                <h5>{{ vehicle.vehicle_topspeed }}</h5>
                <small>Top Speed</small>
              </div>
              <div class="col-md-4">
                <h5>{{ vehicle.vehicle_acceleration }}</h5>
                <small>0-100 km/h</small>
              </div>
            </div>
          </div>
          <form method="post" action="{% url 'vehicle:vehicle_checkout' %}">
            {% csrf_token %}
            <input type="number" name="veh_id" value="{{ vehicle.id }}" hidden>
            <h4 class="mt-5">Color:</h4>
            <div class="row mt-2 align-items-center text-center">
              <div class="col-6">
                <input type="radio"
                       class="btn-check"
                       value="{{ vehicle.vehicle_image_1_name }}"
                       name="colorOptions"
                       id="colorOption1"
                       autocomplete="off"
                       checked>
                <label class="btn btn-outline-primary w-100" for="colorOption1">{{ vehicle.vehicle_image_1_name }}</label>
              </div>
              <div class="col-6">
                <input type="radio"
                       class="btn-check"
                       value="{{ vehicle.vehicle_image_2_name }}"
                       name="colorOptions"
                       id="colorOption2"
                       autocomplete="off">
                <label class="btn btn-outline-primary w-100" for="colorOption2">{{ vehicle.vehicle_image_2_name }}</label>
              </div>
              <div class="col-6 mt-2">
                <input type="radio"
                       class="btn-check"
                       value="{{ vehicle.vehicle_image_3_name }}"
                       name="colorOptions"
                       id="colorOption3"
                       autocomplete="off">
                <label class="btn btn-outline-primary w-100" for="colorOption3">{{ vehicle.vehicle_image_3_name }}</label>
              </div>
              <div class="col-6 mt-2">
                <input type="radio"
                       class="btn-check"
                       value="{{ vehicle.vehicle_image_4_name }}"
                       name="colorOptions"
                       id="colorOption4"
                       autocomplete="off">
                <label class="btn btn-outline-primary w-100" for="colorOption4">{{ vehicle.vehicle_image_4_name }}</label>
              </div>
            </div>
            <h4 class="mt-5">Wheel:</h4>
            <div class="row mt-2 align-items-center text-center">
              <div class="col">
                <input type="radio"
                       class="btn-check"
                       name="wheelOptions"
                       id="wheelOption1"
                       autocomplete="off"
                       value="{{ vehicle.vehicle_wheel_1_name }}"
                       checked>
                <label class="btn btn-outline-primary" for="wheelOption1">
                  <img src="{{ vehicle.vehicle_wheel_1_image }}"
                       width="50"
                       height="50"
                       alt="wheel" />
                </label>
              </div>
              <div class="col">
                <input type="radio"
                       class="btn-check"
                       name="wheelOptions"
                       id="wheelOption2"
                       autocomplete="off"
                       value="{{ vehicle.vehicle_wheel_2_name }}">
                <label class="btn btn-outline-primary" for="wheelOption2">
                  <img src="{{ vehicle.vehicle_wheel_2_image }}"
                       width="50"
                       height="50"
                       alt="wheel" />
                </label>
              </div>
            </div>
            <h4 class="mt-5">Interior:</h4>
            <div class="row mt-2">
              <div class="col">
                <input type="radio"
                       value="White"
                       class="btn-check"
                       name="interiorOptions"
                       id="interiorOption1"
                       autocomplete="off"
                       checked>
                <label class="btn btn-outline-primary" for="interiorOption1">White</label>
                <input type="radio"
                       value="Black"
                       class="btn-check"
                       name="interiorOptions"
                       id="interiorOption2"
                       autocomplete="off">
                <label class="btn btn-outline-primary" for="interiorOption2">Black</label>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-md-7 my-auto">
                {% load humanize %}
                <h5>₱{{ vehicle.vehicle_price|intcomma }}</h5>
              </div>
              <div class="col-md-5 my-auto">
                <button type="submit" class="btn btn-primary">Order Now</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.7.1.min.js"
          integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
          crossorigin="anonymous"></script>
  <script src="{% static 'nav.js' %}"></script>
  <script src="{% static 'carousel.js' %}"></script>
{% endblock content %}

vehicles/templates/vehicle_checkout.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Order Checkout | Tesla
{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'checkout.css' %}">
{% endblock css %}
{% block content %}
{% block nav %}{% endblock nav %}
    <div class="row mt-5">
        <div class="col-75">
            <div class="container">
                <form method="post" action="{% url 'vehicle:confirmOrder' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-50">
                            <h3>Billing Address</h3>
                            <label for="fname">
                                <i class="fa fa-user"></i> Full Name
                            </label>
                            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
                            <label for="email">
                                <i class="fa fa-envelope"></i> Email
                            </label>
                            <input type="text" id="email" name="email" placeholder="john@example.com">
                            <label for="adr">
                                <i class="fa fa-address-card-o"></i> Address
                            </label>
                            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
                            <label for="city">
                                <i class="fa fa-institution"></i> City
                            </label>
                            <input type="text" id="city" name="city" placeholder="New York">
                            <div class="row">
                                <div class="col-50">
                                    <label for="state">State</label>
                                    <input type="text" id="state" name="state" placeholder="NY">
                                </div>
                                <div class="col-50">
                                    <label for="zip">Zip</label>
                                    <input type="text" id="zip" name="zip" placeholder="10001">
                                </div>
                            </div>
                        </div>
                        <div class="col-50">
                            <h3>Payment</h3>
                            <label for="fname">Accepted Cards</label>
                            <div class="icon-container">
                                <i class="fa fa-cc-visa" style="color:navy;"></i>
                                <i class="fa fa-cc-amex" style="color:blue;"></i>
                                <i class="fa fa-cc-mastercard" style="color:red;"></i>
                                <i class="fa fa-cc-discover" style="color:orange;"></i>
                            </div>
                            <label for="cname">Name on Card</label>
                            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
                            <label for="ccnum">Credit card number</label>
                            <input type="text"
                                   id="ccnum"
                                   name="cardnumber"
                                   placeholder="1111-2222-3333-4444">
                            <label for="expmonth">Exp Month</label>
                            <input type="text" id="expmonth" name="expmonth" placeholder="September">
                            <div class="row">
                                <div class="col-50">
                                    <label for="expyear">Exp Year</label>
                                    <input type="text" id="expyear" name="expyear" placeholder="2018">
                                </div>
                                <div class="col-50">
                                    <label for="cvv">CVV</label>
                                    <input type="text" id="cvv" name="cvv" placeholder="352">
                                </div>
                            </div>
                        </div>
                    </div>
                    <label>
                        <input type="checkbox" checked="checked" name="sameadr">
                        Shipping address same as billing
                    </label>
                    <input name="total" value="{{ vehicle.vehicle_price }}" hidden>
                    <input name="custom_veh_id" value="{{ custom_vehicle.id }}" hidden>
                    <input type="submit" value="Continue to checkout" class="btn">
                </form>
            </div>
        </div>
        <div class="col-25">
            <div class="container">
                <h4>
                    Your Order
                    <span class="price" style="color:black">
                        <i class="fa fa-shopping-cart"></i>
                        <b>3</b>
                    </span>
                </h4>
                <p>
                    <a class="text-reset">Model:</a> <span class="price">{{ vehicle.vehicle_name }}</span>
                </p>
                <p>
                    <a class="text-reset">Color:</a> <span class="price">{{ custom_vehicle.vehicle_custom_color }}</span>
                </p>
                <p>
                    <a class="text-reset">Wheel:</a> <span class="price">{{ custom_vehicle.vehicle_custom_wheels}} </span>
                </p>
                <p>
                    <a class="text-reset">Interior:</a> <span class="price">{{ custom_vehicle.vehicle_custom_interior }}</span>
                </p>
                <hr>
                {% load humanize %}
                <p>
                    Total <span class="price" style="color:black"><b>₱{{ vehicle.vehicle_price|intcomma }}</b></span>
                </p>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
{% endblock content %}